version: "3.7"

services:
  # 漏洞靶场，用户名：admin,密码：password
  web-dvwa:
    container_name: web-dvwa
    image: vulnerables/web-dvwa # https://hub.docker.com/r/vulnerables/web-dvwa
    ports:
      - 8080:80

  nikto:
    image: huafeihuao0/nikto:2.1.6
    depends_on:
      - web-dvwa
    # 目录爆破
#    command: -h http://web-dvwa -c all
    entrypoint: sleep 10000
