version: '3'

services:
  dongtai-mysql:
    image: dongtai/dongtai-mysql:1.3.1

  dongtai-redis:
    image: dongtai/dongtai-redis:1.3.1

  dongtai-webapi:
    image: dongtai/dongtai-webapi:1.3.1
    depends_on:
      - dongtai-mysql
    volumes:
      - ./asset/config.ini:/opt/dongtai/webapi/conf/config.ini

  dongtai-web:
    image: dongtai/dongtai-web:1.3.1
    depends_on:
      - dongtai-webapi
    volumes:
      - ./asset/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80

  dongtai-openapi:
    image: dongtai/dongtai-openapi:1.3.1
    depends_on:
      - dongtai-mysql
    volumes:
      - ./asset/config.ini:/opt/dongtai/openapi/conf/config.ini

  dongtai-engine:
    image: dongtai/dongtai-engine:1.3.1
    depends_on:
      - dongtai-mysql
    volumes:
      - ./asset/config.ini:/opt/dongtai/engine/conf/config.ini

  dongtai-engine-task:
    image: dongtai/dongtai-engine:1.3.1
    depends_on:
      - dongtai-engine
      - dongtai-mysql
    command: [ "/opt/dongtai/engine/docker/entrypoint.sh", "task" ]
    volumes:
      - ./asset/config.ini:/opt/dongtai/engine/conf/config.ini

  dongtai-java-agent-docker-demo:
    image: dongtai/dongtai-java-agent-demo:0.0.1
    depends_on:
      - dongtai-openapi
    network_mode: host
    volumes:
      - ./asset/agent.jar:/opt/agent.jar
    environment:
      - JAVA_TOOL_OPTIONS='-javaagent:/opt/agent.jar'

