version: '3'

services:
  webgoat:
    image: webgoat/webgoat-8.0:latest
    network_mode: host
    volumes:
      - ./asset/agent.jar:/opt/agent.jar
    entrypoint: java -javaagent:/opt/agent.jar -Dproject.name=webgoat -Djava.security.egd=file:/dev/./urandom -jar /home/webgoat/webgoat.jar
