version: "3.7"

services:
  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - 27017

  # 测试用户名：admin 密码：Admin_123
  nodegoat:
    image: huafeihuao0/nodegoat:master
    depends_on:
      - mongo
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4000:4000"
