# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# Purpose: Build local containers for the Mutillidae environment

version: '3.7'

volumes:
  ldap_data:
  ldap_config:

# Create network segments for the containers to use
networks:
  datanet:
  ldapnet:

services:
  database:
    image: webpwnized/mutillidae:database
    networks:
      - datanet

  database_admin:
    depends_on:
      - database
    image: webpwnized/mutillidae:database_admin
    ports:
      - 127.0.0.1:81:80
    networks:
      - datanet

  www:
    depends_on:
      - database
      - directory
    image: webpwnized/mutillidae:www
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - datanet
      - ldapnet

  directory:
    image: webpwnized/mutillidae:ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - ldapnet

  directory_admin:
    depends_on:
      - directory
    image: webpwnized/mutillidae:ldap_admin
    ports:
      - 127.0.0.1:82:80
    networks:
      - ldapnet
