version: '3'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=w5_12345678
    volumes:
      - ./asset/conf.d:/etc/mysql/conf.d
      - ./asset/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password

  # admin/12345678
  w5:
    image: w5team/w5
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=w5_12345678
      - MYSQL_DATABASE=w5_db
    ports:
      - 8888:8888
    tty: true
    entrypoint: /root/start
