version: '3'

services:
  postgres:
    image: postgres:14.2 # https://hub.docker.com/_/postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=faraday

  faraday:
    image: faradaysec/faraday:3.19.0 # https://hub.docker.com/r/faradaysec/faraday
    depends_on:
      - postgres
    environment:
      - PGSQL_HOST=postgres
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=example
      - PGSQL_DBNAME=faraday
    volumes:
      - ./volumes/logs/alembic.log:/home/faraday/.faraday/logs/alembic.log
    ports:
      - 5985:5985

