version: '3'

services:
  mongo:
    image: mongo:4.0.13-xenial
    hostname: mongo

  astra:
    image: huafeihuao0/astra:394d538
    hostname: astra
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongo
    links:
      - mongo
    ports:
      - 8094:8094
