Version: '2.4'

services:
  omnidb:
    image: registry.fit2cloud.com/jumpserver/omnidb:${Version}
    container_name: jms_omnidb
    restart: always
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "ps axu | grep -v 'grep' | grep 'omnidb'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/omnidb/data:/opt/omnidb/data
    networks:
      - net

  razor:
    image: registry.fit2cloud.com/jumpserver/razor:${Version}
    container_name: jms_razor
    restart: always
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "ps axu | grep -v 'grep' | grep 'razor'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - 3389:3389
    volumes:
      - ${VOLUME_DIR}/razor/data:/opt/razor/data
    networks:
      - net
