version: '2'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1

  frontend:
    image: thinkst/canarytokens
    container_name: frontend
    hostname: frontend
    links:
      - redis
    env_file:
      - asset/frontend.env
    command: bash -c "rm -f frontend.pid; twistd -noy frontend.tac --pidfile=frontend.pid"

  # 交换机
  switchboard:
    image: thinkst/canarytokens
    container_name: switchboard
    hostname: switchboard
    ports:
      - "53:53"
      - "53:53/udp"
      - "25:25"
      - "3306:3306"
      - "6443:6443"
      - "51820:51820/udp"
    links:
      - redis
    env_file:
      - asset/switchboard.env
    command: bash -c "rm -f switchboard.pid; twistd -noy switchboard.tac --pidfile=switchboard.pid"

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - frontend
      - switchboard
    command: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
