version: "3.7"

services:
  # 漏洞靶场，用户名：admin,密码：password
  web-dvwa:
    container_name: web-dvwa
    image: vulnerables/web-dvwa # https://hub.docker.com/r/vulnerables/web-dvwa
    ports:
      - 8080:80

  xray:
    image: huafeihuao0/xray:1.8.4
    depends_on:
      - web-dvwa
    volumes:
      - ./output:/opt
    entrypoint: xray webscan --basic-crawler http://web-dvwa --html-output vuln.html
