version: "3.4"

x-opencve-defaults: &opencve_defaults
    image: huafeihuao0/opencve:${OPENCVE_VERSION}
    volumes:
        - ${OPENCVE_CONFIG_PATH}:/app/opencve.cfg:ro

services:
    webserver:
        <<: *opencve_defaults
        container_name: webserver
        depends_on:
            - postgres
        command: webserver -b 0.0.0.0:8000
        ports:
            - ${OPENCVE_PORT:-8000}:8000

    celery_beat:
        <<: *opencve_defaults
        container_name: celery_beat
        depends_on:
            - webserver
            - redis
        command: celery-beat
    celery_worker:
        <<: *opencve_defaults
        container_name: celery_worker
        depends_on:
            - webserver
            - redis
        command: celery-worker

    redis:
        container_name: redis
        image: redis:buster
        ports:
            - 127.0.0.1:${REDIS_PORT:-6379}:6379
    postgres:
        container_name: postgres
        image: postgres:11
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-opencve}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-opencve}
            POSTGRES_DB: opencve
            PGDATA: /var/lib/postgreqsql/data
        ports:
            - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
